export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  PRODUCT_DATA_VALIDATION_FAILED = 'PRODUCT_DATA_VALIDATION_FAILED',
  PRODUCT_ID_NOT_FOUND = 'PRODUCT_ID_NOT_FOUND',
  JOB_ID_NOT_FOUND = 'JOB_ID_NOT_FOUND',
  INVALID_MIMETYPE = 'INVALID_MIMETYPE',
}
